
// require('./api/user-test')
// require('./api/stack-test')
// require('./api/organization-test')
// require('./api/role-test')
// require('./api/contentType-test')
// require('./api/contentType-delete-test')
// require('./api/stack-share')
// require('./api/asset-test')
// require('./api/delete-test')
require('./api/extension-test')
// require('./api/extension-delete-test')
