language: node_js
node_js:
- '8'
- '10'
sudo: false
branches:
  except:
  - gh-pages
before_script:
- npm install
- npm install -g jsdoc
script:
- npm test
after_success:
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
env:
  global:
    secure: ***REMOVED***