format_version: 3
pipelines:
  sdk-basic-sanity:
    group: sdk
    label_template: ${git[:7]}
    lock_behavior: none
    display_order: -1
    timer:
      spec: 0 30 5,12 ? * MON-FRI
      only_on_changes: false
    materials:
      git:
        git: git@github.com:contentstack/contentstack-management-javascript.git
        shallow_clone: true
        auto_update: true
        branch: next
        blacklist:
          - '**/*'
    stages:
      - sanity:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          secure_variables:
            HOST: AES:9OPdody14ZUdz7KhJEZSFQ==:Sc766oAo+M44igMM0neq8KHHNvN/iaYp4vM7Sy6nA/8=
            EMAIL: AES:IXm51xw93AglgkzK6xgetQ==:OV/TXVed9pCw9o+HOdNMEG7AIay4oOb/hO5ODfckIP8=
            PASSWORD: AES:9ezh6KYBrvDbeZ6MV1onTw==:p2iX7OZ09djPDBsBev63lQ==
            ORGANIZATION: AES:d710nHeFa8G20/k8YVXpAg==:mPIxDHLw8pQKNFfNb+hnPHUNUYcfEr77Bm6BcVzbW5s=
            API_KEY: AES:5Ns0MjiD1o492KH6bsTS7Q==:FSIyMX7Kr4RTJWEHh/P/0Wx1q+wJ4JgNtedI2hecpPk=
            SLACK_SIGNING_SECRET: AES:7cDGnDJ0DuUfctAtJrZUeA==:VC8RY412yLuW9Qkogz2u+xgJFqY7Wnzvv2Zilt57/zUgK6cE917WHGGcPzPadT2a
            SLACK_BOT_TOKEN: AES:eJPkHvMQgRFaHwjsh+7Twg==:F6kY4FNpvX/l6/Wga7qv0qWf3wXPFmzxFrturOT6qFyM2i8QyeIqMjI1nNLvmE+Ng1Xyd+Mg6W//qoRTcKxh7Q==
            SLACK_CHANNEL: AES:XXcllVy4fPZS9B/7727lsw==:97h5rk6do9LZdp+xc7WLO58D05HAhMU6KsM8881bgN5acpHCA8YNTQcEEw414Dzt
          jobs:
            sanity:
              elastic_profile_id: k8s-cicd-npm18-build-coverage
              timeout: 0
              artifacts:
                - test:
                    source: mochawesome-report
                    destination: test-results
              tasks:
                - exec:
                    arguments:
                      - -c
                      - npm install
                    command: sh
                - exec:
                    arguments:
                      - -c
                      - npm run test:sanity
                    command: sh
                - exec:
                    arguments:
                      - -c
                      - npm run test:sanity-report
                    command: sh
