format_version: 3
pipelines:
  sdk-stage-sanity:
    group: sdk
    label_template: ${git[:7]}
    lock_behavior: none
    display_order: 1
    materials:
      git:
        git: git@github.com:contentstack/contentstack-management-javascript.git
        shallow_clone: true
        auto_update: true
        branch: next
    stages:
      - sanity:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          secure_variables:
            HOST: AES:EBR2p0u0m4vhvldIum06tw==:jurRR3F930A26pW+nSHb2X2J/lBQmYu1CRuvkhDT/us=
            EMAIL: AES:rJhZS8T0XAAN2w8XVO7i8Q==:ZNn+rEUxJl21UucATOV+Tg0GzXytyVy72BHvR/dp6qg=
            PASSWORD: AES:SU4/0ZQmKfPkJ2opr6cjbA==:zUSP7Ua4Ddd/fVc/KinvyQ==
            ORGANIZATION: AES:j/9zyTpbrD4AO2nNuRjKgQ==:VB0SUf0KD2SXn8rYHxGqvrRHYoFr8jjKa/NpLnRhH94=
            API_KEY: AES:37x7hQuXE8W7Y8nXzPnTdg==:uBOG3ckJAkvH7eNOBuqJQ4SpRummT3RlF4QLGBRFogM=
            SLACK_CHANNEL: AES:MyYQPBmZYdfThdwP1/DPHw==:Rci4yTJuwvvbo8OIlncX0ZNGfACFj6T6/0D6QDC4ICg=
            SLACK_SIGNING_SECRET: AES:BeWp9X9WMX3xkr6Lot/GBg==:zf07MucKiWIXN0Msd5KDBXbPTVY0l5gUTFFz//NSJbljJPV0IvjrgN7xfuybA1FR
            SLACK_BOT_TOKEN: AES:SG41CXPxT9ZDNVPfzypxjA==:8MQNsQ+nynZz59zulhfsZua3S/1PeLNIA2SppIZ3pter4ndk6FRsqyLDRfJPCJTMUaBiVMqIUsJYenBgrXqzng==
          jobs:
            sanity:
              elastic_profile_id: k8s-cicd-npm18-build-coverage
              timeout: 0
              artifacts:
                - test:
                    source: mochawesome-report
                    destination: test-results
              tasks:
                - exec:
                    arguments:
                      - -c
                      - npm install
                    command: sh
                - exec:
                    arguments:
                      - -c
                      - npm run test:sanity
                    command: sh
                - exec:
                    arguments:
                      - -c
                      - npm run test:sanity-report
                    command: sh