import { client, __RewireAPI__ as createClientRewireApi } from '../../lib/contentstack.js'
import { expect } from 'chai'
import { describe, it } from 'mocha'
import packages from '../../package.json'
import sinon from 'sinon'
const SDK = `contentstack-management-javascript/${packages.version}`

describe('Contentstack HTTP Client', () => {
  it('Contentstack Http Client Object successful', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    var clients = client()
    expect(clients).to.not.equal(null, 'Contentstack Client should not null')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  it('Contentstack Http Client X-User-Agent Header', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client()
    expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Default host name not match')
    expect(createHttpClientStub.args[0][0].headers['X-User-Agent']).to.be.equal(SDK, 'Default host name not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  it('Contentstack Http Client Authtoken', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client({ authtoken: 'token' })
    expect(createHttpClientStub.args[0][0].authtoken).to.be.equal('token', 'Authtoken not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  it('Contentstack Http Client Default Host', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client()
    expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Default host name not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  it('Contentstack Http Client Default Host Custom', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client({ defaultHostName: 'contentstack.com' })
    expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('contentstack.com', 'Default host name not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  it('Contentstack Http Client User-Agent Header', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client()
    const headerParts = createHttpClientStub.args[0][0].headers['User-Agent'].split('; ')
    expect(headerParts[0]).to.be.match(/^sdk contentstack-management-javascript\/.+/, 'User agent sdk does not match')
    expect(headerParts[1]).to.be.match(/^platform (.+\/.+|browser)/, 'User agent platform does not match')
    expect(headerParts[2]).to.be.match(/^os .+/, 'User agent os does not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  it('Contentstack Http Client User-Agent Header Custom', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client({ application: 'myApplication/1.0.0', integration: 'myIntegration/1.2.0', feature: 'feature' })
    const headerParts = createHttpClientStub.args[0][0].headers['User-Agent'].split('; ')
    expect(headerParts[0]).to.be.equal('app myApplication/1.0.0', 'User agent app does not match')
    expect(headerParts[1]).to.be.equal('integration myIntegration/1.2.0', 'User agent integration does not match')
    expect(headerParts[2]).to.be.equal('feature feature', 'User agent feature does not match')
    expect(headerParts[3]).to.be.match(/^sdk contentstack-management-javascript\/.+/, 'User agent sdk does not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })
  it('should have valid format of early_access headers when early_access is passed', done => {
    createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
    const createHttpClientStub = sinon.stub()
    createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
    createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
    client({ early_access: ['ea1', 'ea2'] })
    expect(createHttpClientStub.args[0][0].headers.early_access).to.be.eql('ea1,ea2', 'Early access does not match')
    createClientRewireApi.__ResetDependency__('httpClient')
    createClientRewireApi.__ResetDependency__('contentstackClient')
    done()
  })

  describe('Region Configuration', () => {
    it('should use default NA region when no region is specified', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client()
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Should default to NA region')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should set EU region endpoint when region is eu', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'eu' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('eu-api.contentstack.com', 'Should use EU region endpoint')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should set AU region endpoint when region is au', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'au' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('au-api.contentstack.com', 'Should use AU region endpoint')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should set Azure NA region endpoint when region is azure-na', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'azure-na' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('azure-na-api.contentstack.com', 'Should use Azure NA region endpoint')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should set Azure EU region endpoint when region is azure-eu', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'azure-eu' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('azure-eu-api.contentstack.com', 'Should use Azure EU region endpoint')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should set GCP NA region endpoint when region is gcp-na', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'gcp-na' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('gcp-na-api.contentstack.com', 'Should use GCP NA region endpoint')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should set GCP EU region endpoint when region is gcp-eu', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'gcp-eu' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('gcp-eu-api.contentstack.com', 'Should use GCP EU region endpoint')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should accept region aliases - us', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'us' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Should accept us alias for NA')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should accept region aliases - aws-na', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'aws-na' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Should accept aws-na alias for NA')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should accept region aliases - aws_na', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'aws_na' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Should accept aws_na alias for NA')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should accept region aliases - azure_na', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'azure_na' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('azure-na-api.contentstack.com', 'Should accept azure_na alias for Azure NA')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should throw error for invalid region', done => {
      try {
        client({ region: 'invalid-region' })
        done(new Error('Should have thrown an error for invalid region'))
      } catch (error) {
        expect(error.message).to.contain('Invalid region', 'Error message should indicate invalid region')
        expect(error.message).to.contain('invalid-region', 'Error message should include the invalid region name')
        done()
      }
    })

    it('should handle region parameter case-sensitively', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'na' })
      expect(createHttpClientStub.args[0][0].defaultHostName).to.be.equal('api.contentstack.io', 'Lowercase region should work')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })

    it('should pass region to HTTP client configuration', done => {
      createClientRewireApi.__Rewire__('client', { create: sinon.stub() })
      const createHttpClientStub = sinon.stub()
      createClientRewireApi.__Rewire__('httpClient', createHttpClientStub)
      createClientRewireApi.__Rewire__('contentstackClient', sinon.stub().returns({}))
      client({ region: 'eu' })
      expect(createHttpClientStub.args[0][0].region).to.be.equal('eu', 'Region should be passed to HTTP client')
      createClientRewireApi.__ResetDependency__('httpClient')
      createClientRewireApi.__ResetDependency__('contentstackClient')
      done()
    })
  })
})
